# Generated by Django 4.1 on 2023-05-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                ("anm_id", models.IntegerField(primary_key=True, serialize=False)),
                ("anm_name", models.CharField(max_length=45)),
                ("anm_spcs", models.CharField(max_length=45)),
                ("anm_city", models.CharField(max_length=45)),
                ("anm_sex", models.CharField(max_length=20)),
                ("anm_birth", models.DateField(blank=True, null=True)),
                ("anm_rct", models.CharField(max_length=45)),
                ("anm_img", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                ("area_id", models.IntegerField(primary_key=True, serialize=False)),
                ("area_name", models.CharField(max_length=20)),
                ("area_loc", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Parttime",
            fields=[
                ("pt_id", models.IntegerField(primary_key=True, serialize=False)),
                ("pt_name", models.IntegerField()),
                ("pt_start", models.TimeField()),
                ("pt_end", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("zone_id", models.IntegerField(primary_key=True, serialize=False)),
                ("zone_name", models.CharField(max_length=20)),
                ("zone_max", models.IntegerField()),
                ("zone_loc", models.CharField(max_length=45)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Zoo.area"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckLog",
            fields=[
                (
                    "anm_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Zoo.animal",
                    ),
                ),
                ("clog_tm", models.TimeField()),
                ("clog_food", models.CharField(max_length=45)),
                ("clog_bf", models.IntegerField()),
                ("clog_lch", models.IntegerField()),
                ("clog_dn", models.IntegerField()),
                ("clog_mc", models.CharField(blank=True, max_length=45, null=True)),
                ("clog_mm", models.IntegerField(blank=True, null=True)),
                ("clog_lm", models.IntegerField(blank=True, null=True)),
                ("clog_em", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Zookeeper",
            fields=[
                ("zkp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("zkp_name", models.CharField(max_length=11)),
                ("zkp_call", models.CharField(max_length=11)),
                ("zkp_carr", models.CharField(max_length=10)),
                (
                    "pt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Zoo.parttime"
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Zoo.zone"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetailLog",
            fields=[
                ("dlog_id", models.IntegerField(primary_key=True, serialize=False)),
                ("dlog_cgr", models.CharField(max_length=20)),
                ("dlog_con", models.CharField(max_length=100)),
                ("dlog_dt", models.DateTimeField()),
                (
                    "anm_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Zoo.animal"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animal",
            name="zone_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Zoo.zone"
            ),
        ),
    ]
